### ISSUE TITLE
feature request: ability to see the mod's description in the installed mods menu

### ISSUE THREAD

**Issue by calamitywoah** [0x0ade/CelesteNet#144]
self-explanatory.

going into the installed mods menu and directly viewing the description there is much easier and less time consuming than searching for the mod in the download mods menu.

it would be a great utility for finding out which mods can be deleted, and which shouldnt be

**Comment by Erikgobrrr** [comment]
for future reference, close it as "not planned" instead of "completed" if its a "nvm" kind of thing

<img width="336" height="247" alt="Image" src="https://github.com/user-attachments/assets/e9dcdba0-21f8-4374-a5e7-ba9e7ccecc5f" />

its heavily recommended to reclose this as "not planned" in order to convey the info correctly
